# Generated by Django 5.0.1 on 2025-12-26 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField()),
                ('rent', models.FloatField(default=0)),
                ('loan_repayment', models.FloatField(default=0)),
                ('insurance', models.FloatField(default=0)),
                ('savings_percentage', models.FloatField()),
                ('disposable_income', models.FloatField()),
                ('savings_goal', models.FloatField()),
                ('allocations', models.JSONField()),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
